spring:
  application:
    name: oauth-client-user
  redis:
    database: 2
    host: localhost
    port: 6379
    #password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 6101

security:
  oauth2:
    client:
      #client-id: user-client
      #client-secret: user-secret-8888
      user-authorization-uri: http://localhost:6001/oauth/authorize
      access-token-uri: http://localhost:6001/oauth/token
      client-id: test_client
      client-secret: 123456
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:6001/oauth/check_token
debug: true
